repos:
-   repo: https://github.com/pre-commit/mirrors-black
    rev: v21.10b0
    hooks:
    - id: black
-   repo: https://github.com/pre-commit/mirrors-flake8
    rev: v3.9.2
    hooks:
    - id: flake8
